### PR TITLE
Fixes #25

### LINKED ISSUE #25: Add State Info to Statistic-Label Page
We would like to add another button to the top of the statistic label page to hold info about all the states. There should be a filter for each state.

[AppInfoTable.xlsx](https://github.com/USGS-WiM/StreamStats-Setup/files/8188281/AppInfoTable.xlsx)

### PR DESCRIPTION
**Pull request by harper-wavra**
Add two new tabs, Application Information and General StreamStats Information. 

After you select a region the relevant information should appear in the tables.

### CODE REVIEW

**Review by amedenblik — CHANGES_REQUESTED** [review]
- [ ] When "None" is selected for the "Application Information" or "General StreamStats Information" tabs, maybe the table/labels should not appear 
- [x] In the "Application Information" or "General StreamStats Information" tabs, when I select a Region and then select "None" again, the loader appears and doesn't seem to stop loading
- [ ] Is there possibly a different name for "Application Information"? It's not clear to me, based on the name of the tab, what information will be shown. Maybe Pete/etc. have other ideas. Or if that name was his idea, that's fine too. Alternatively, a more specific description (like in the "Statistic Types" tab) would be fine. 
- [ ] Is there possibly a different name for "General StreamStats Information"? It's not clear to me, based on the name of the tab, what information will be shown. I thought it would be general information about StreamStats, not region-based info. Maybe "Region Information"? 
- [ ] I think the "General StreamStats Information" content would look nice as a two-column table
- [ ] Should we change all references to "state"s (ex. "Select a state to view general streamstats information about that state.") to "region", since not all Regions are states?

**Comment by harper-wavra** [comment]
I agreed about the renaming "Application Information" and "General StreamStats Information", I will ask Pete about that. 

NSS uses "Study Area" as the language for states/regions, so I think changing it to that could be good.

**Comment by amedenblik** [comment]
> NSS uses "Study Area" as the language for states/regions, so I think changing it to that could be good.

StreamStats uses "State / Region" for the Regions and "Study Area" for the delineated basin, so I'm thinking "State / Region" might be more familiar to users. 
image

**Comment by harper-wavra** [comment]
- [ ] change into single tab "regional information"
- [ ] add url parameters

**Review by amedenblik — APPROVED** [review]

**Pull request merged**
